### ISSUE TITLE
Adding Support for Javascript to run tests

### ISSUE THREAD

**Issue by DannyEnsink** [maximehamm/tzatziki#29]
When clicking the "Run Test" arrow all tests always fail, it seems Javascript running of tests like this doesn't work (yet)? Will you consider adding support for it?

I'm using Cucumber/Gherkin with Cypress in Rider IDE.

![image](https://user-images.githubusercontent.com/8476848/148404820-bf14170d-8630-4ef5-96b0-54639bf59395.png)
![image](https://user-images.githubusercontent.com/8476848/148405417-6f1e145b-c3c3-47c4-bb24-3a1a7207cae4.png)

**Comment by maximehamm** [comment]
Hello Danny

Tu run a test you have to install some other plugin like [cucumber for Java](https://plugins.jetbrains.com/plugin/7212-cucumber-for-java), [cucumber for Scala](https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala), [cucumber.js](https://plugins.jetbrains.com/plugin/7418-cucumber-js), etc... 

Cucumber+ added the support to run a **SINGLE LINE** of a scenario outline (i.e one table line), which is not supported by any of previous languages. But Cucumber+ did this **ONLY FOR JAVA** because only  [cucumber for Java](https://plugins.jetbrains.com/plugin/7212-cucumber-for-java) was designed for it...

Once this is said, it is still strange that all your tests are down... did you install [cucumber.js](https://plugins.jetbrains.com/plugin/7418-cucumber-js) ? I noticed that the use of both [cucumber.js](https://plugins.jetbrains.com/plugin/7418-cucumber-js) and [cucumber for Java](https://plugins.jetbrains.com/plugin/7212-cucumber-for-java) does not work well...

Hope this will help,

Kind regards

Maxime

**Comment by DannyEnsink** [comment]
Current plug-ins installed related to testing are: Cucumber.js, Cucumber +, Gherkin and Cypress Support. No Java is used and cucumber for Java cant be installed in Rider (as Rider is focussed for C#, not Java).

**Comment by maximehamm** [comment]
Hi
I think you should investigate project configuration... tests are launched by Cucumber.js... 
May be, to be sure that there is no side-effect due tu cucumber+, you can try to deactivate it...

**Comment by DannyEnsink** [comment]
Hi,
Been digging through all the project configurations but I haven't found a solution just yet. Cucumber+ is disabled at this point and even with Cypress Support Pro, the tests are still launched by Cucumber.js. I can create manual configuration with the Cypress configurations, but the sidebar green arrow still only runs as Cucumber.js.

Any help is appreciated very much.

**Comment by DannyEnsink** [comment]
I found a fix, which ended up being rather simple.

Inside Rider IDE go to File > Settings... > Languages & Frameworks > Cypress > Cypress config file path.

By default this field is empty and the IDE is supposed to look for the cypress.json file by itself, but in our case it seems to not being able to find it (although the IDE isn't saying it cannot find it).

So the solution ended up being to put the path to the cypress.json file there and everything started to work.
